maqueen.servo_run(maqueen.Servos.S1, 0)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 20)
basic.pause(2000)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 19)
maqueen.servo_run(maqueen.Servos.S1, 55)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CCW, 30)
basic.pause(2000)
maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CCW, 20)
basic.pause(2000)
maqueen.motor_stop(maqueen.Motors.ALL)
maqueen.servo_run(maqueen.Servos.S1, 20)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CCW, 70)
basic.pause(2000)
maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 0)
basic.pause(5000)
maqueen.motor_stop(maqueen.Motors.ALL)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 20)
basic.pause(5000)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 0)
maqueen.servo_run(maqueen.Servos.S1, 55)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 100)
basic.pause(2000)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 0)
maqueen.servo_run(maqueen.Servos.S1, 55)
maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CCW, 80)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CCW, 0)